### ISSUE TITLE
Hydroelastic contact / pressure field model

### ISSUE THREAD

**Issue by AlexanderFabisch** [AlexanderFabisch/distance3d#43]
## Current State

<img src="https://user-images.githubusercontent.com/869592/181867062-c5f94b8d-c5e2-4392-84d3-d1d9c1803a7f.png" width=30% /><img src="https://user-images.githubusercontent.com/869592/182720287-f017770e-5923-445d-82d1-0293f736d881.png" width=30% />

<img src="https://user-images.githubusercontent.com/869592/186017246-7b32493b-3f17-4db3-b873-59d3d908da48.gif" width=30% /><img src="https://user-images.githubusercontent.com/869592/185766530-78bc1a2a-39a2-467b-bdb7-834e29ea62ea.gif" width=30% />

<img src="https://user-images.githubusercontent.com/869592/186764281-ac0e7f98-dfcd-4671-9b67-c03484d65c62.gif" width=60% />

## Literature

* Elandt et al.: A pressure field model for fast, robust approximation of net contact force and moment between nominally rigid objects (2018)
    * PDF: https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8968548
    * preprint: https://www.researchgate.net/publication/332669476_A_pressure_field_model_for_fast_robust_approximation_of_net_contact_force_and_moment_between_nominally_rigid_objects
    * Symbols
        * epsilon: potentials of vertices, closest distance to surface of the mesh
        * nu: vertex of a tetrahedron
        * zeta: barycentric coordinates of a point in terms of vertices of a tetrahedron; non-negative, sum to one
        * X: transforms zeta to Cartesian frame; columns are the vertices of the tetrahedron, last row is 1
* Huang et al.: An Efficient Implementation of Pressure Field Models
    * PDF: https://www.ekzhang.com/assets/pdf/Hydroelastics.pdf
    * code: https://github.com/ekzhang/hydroelastics/
* Masterjohn et al.: Velocity Level Approximation of Pressure Field Contact Patches (2022)
    * blog: https://medium.com/toyotaresearch/rethinking-contact-simulation-for-robot-manipulation-434a56b5ec88
    * PDF: https://arxiv.org/pdf/2110.04157.pdf
* Drake
    * user guide: https://drake.mit.edu/doxygen_cxx/group__hydroelastic__user__guide.html
    * API documentation: https://drake.mit.edu/doxygen_cxx/classdrake_1_1geometry_1_1_contact_surface.html
    * video: https://www.youtube.com/watch?v=HL1-yIvwSHI&t=7s

## TODO

- [x] fix broad phase collision detection (sphere / cube) #60 
    - see below for more information
- [x] accelerate broad phase collision detection (with numba?) #60 
- [x] make Young's modulus configurable #62 
- [ ] also: measure Young's modulus of several objects (https://www.uni-bremen.de/fileadmin/user_upload/fachbereiche/fb1/fb1/Physika/Versuche/Mechanik/Anleitung/M15_E_Modul_10_10_16.pdf)
- [x] fix case in which two spheres perfectly overlap
- [ ] add friction force computation
- [x] add example of physics simulation with objects in contact
- [ ] add example with grasp metrics?
- [ ] generate primitive shapes as tetrahedral meshes + potentials
    - [x] sphere ([drake](https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/make_sphere_mesh.h))
    - [x] cube
    - [x] box ([drake](https://github.com/RobotLocomotion/drake/blob/6b4664c2b4c4a7f52d24d16898d0bc2cc7f2b893/geometry/proximity/make_box_mesh.cc))
    - [x] ellipsoid ([drake](https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/make_ellipsoid_mesh.h))
    - [x] cylinder ([drake](https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/make_cylinder_mesh.cc))
    - [x] capsule ([drake](https://github.com/RobotLocomotion/drake/blob/903019faf53b771e8e2fe81222ffd74eae2dc85c/geometry/proximity/make_capsule_mesh.cc))
    - [ ] cone (similar to cylinder or hemisphere of a capsule)
- [x] convex triangular mesh
    - compute tetrahedral mesh with TetWild
    - medial axis?
        - https://3d.bk.tudelft.nl/projects/3dsm/
        - https://yajieyan.github.io/project/voxelcore/
    - potentials: for each vertex, compute the shortest distance to any triangle of the surface mesh #56 
    - store potentials in some file format that will be loaded along with the tetrahedral mesh?
- [x] concave triangular mesh

### Broad Phase Bug

We currently use the [aabbtree](https://aabbtree.readthedocs.io/en/latest/) library for broad phase collision detection. It seems to have a bug as it filters too many potentially overlapping AABBs.

I assume the problem might be in the function `_unique_pairs` of the library.

#### Links

- [R* trees](https://en.wikipedia.org/wiki/R*-tree) - used by another implementation of hydroelastic contacts
- [aabbtree library](https://github.com/kip-hart/AABBTree)
- [tutorial](https://www.azurefromthetrenches.com/introductory-guide-to-aabb-tree-collision-detection/)
- [SpatialIndexing.jl](https://github.com/alyst/SpatialIndexing.jl)

#### How to Reproduce

Uncomment broad phase collision detection in `distance3d/hydroelastic_contact/_broad_phase.py`.

Modify `examples/visualization/vis_pressure_field.py` to the following objects:

```python
import pytransform3d.rotations as pr


rigid_body1 = hydroelastic_contact.RigidBody.make_sphere(0.13 * np.ones(3), 0.15, 2)
cube2origin = np.eye(4)
cube2origin[:3, :3] = pr.active_matrix_from_extrinsic_euler_zyx([0.1, 0.3, 0.5])
cube2origin[:3, 3] = 0.25 * np.ones(3)
rigid_body2 = hydroelastic_contact.RigidBody.make_cube(cube2origin, 0.15)
```

### Generate GIF

```bash
ffmpeg -i Screencast*.mp4 -r 15 -vf scale=512:-1 -ss 00:00:00 -to 00:00:04 hydroelastic_pressure_field.gif
ffmpeg -i Screencast*.mp4 -r 15 -vf scale=512:-1 -filter:v "setpts=0.05*PTS" hydroelastic_pressure_field.gif

ffmpeg -i 'Bildschirmaufnahme 2022-09-02 17:41:36.mp4' img%04d.jpg
convert -resize 50% -delay 5 -loop 0 img*.jpg img.gif
```
